server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.231.108:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"