server:
  port: 3333

spring:
  devtools:
    add-properties: true
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #          uri: git@github.com:LiAnChen1989/springcloud-config.git
          uri: https://github.com/LiAnChen1989/springcloud-config.git
          search-paths:
            - springcloud-config
          default-label: master
          username: LiAnChen1989
          password: Cl@github1989
          skip-ssl-validation: true
#rabbitmq的相关配置
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
#      label: master

eureka:
  client:
    #表示是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    #是否从的eureka server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon实现负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: config-center-3333
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳时间间隔，单位为秒（默认是30秒）
    #    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2



#暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
