server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    #是否从的eureka server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon实现负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳时间间隔，单位为秒（默认是30秒）
    #    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2

#设置feign客户端的超时时间
ribbon:
  #建立链接所用的时间，适用于网络状况正常的情况下，两端链接所用的时间
  ReadTimeout: 5000
  #建立连接后读取资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别控制那个接口
    com.atzybank.springcloud.service.PaymentFeignService: debug
