server:
  port: 8802

spring:
  devtools:
    add-properties: true
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于bindding的整合
          type: rabbit
          environment: #rabbitmq相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型为json，文本设置“text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: A #解决重复消费问题和消息持久化问题，（同一个组不能重复消费，连个不同的组可以重复消费,默认不同组）


eureka:
  client:
    #表示是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    #是否从的eureka server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon实现负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: stream-consumer-8802
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳时间间隔，单位为秒（默认是30秒）
    #    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2



