server:
  port: 9527

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  #payment_route 路由id，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
#            - After
#            - Before
#            - Between
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#            - Cookie=username,cla
#            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性且值为整数的正则表达式

  application:
    name: cloud-gateway

eureka:
  client:
    #表示是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    #是否从的eureka server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon实现负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳时间间隔，单位为秒（默认是30秒）
    #    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2